services:
  - type: web
    name: ua-habitual
    runtime: node
    buildCommand: npm install && npm run build:frontend
    startCommand: npm install && npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
